javascript:
var highlightedText = window.getSelection().toString();
highlightedText = highlightedText.replace("?",".");
highlightedText = highlightedText.replace("!","."); 
highlightedText = highlightedText.replace(/\.\.*/g,".");
var sentences = highlightedText.split(".");
var sentenceCount = (highlightedText.match(/\.\s/g) != null) ? highlightedText.match(/\.\s/g).length : 0;
sentenceCount += (highlightedText.slice(-1) == ".") ? 1:0;
var wordCount = highlightedText.split(" ").length;
var avgWordsPerSentence = (wordCount/sentenceCount).toFixed(2);
var commasCount = highlightedText.split(",").length;
var avgCommasPerSentence = (commasCount/sentenceCount).toFixed(2);
console.log("\n\n\n\n\n\n");
var analysis = "ANALYZED TEXT!\n";
analysis += "Sentences: "+sentenceCount+"\n";
analysis += "Words: "+wordCount+"\n";
analysis += "Avg words/sentence: "+avgWordsPerSentence+"\n";
analysis += "commasCount: "+commasCount+"\n";
analysis += "Avg commas/sentence: "+avgCommasPerSentence+"\n";
console.log(analysis); alert(analysis);
